longhorn:
  ingress:
    enabled: true
    host: longhorn.burau.dev
    tls: true
    tlsSecret: ingress-tls
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
      helm.sh/resource-policy: keep
  defaultBackupStore:
    backupTarget: nfs://192.168.1.2:/volume2/nfs/longhorn
