longhorn:
  ingress:
    enabled: true
    host: longhorn.burau.dev
    tls: true
    tlsSecret: longhorn-ingress-tls
    annotations:
      cert-manager.io/cluster-issuer: cloudflare-issuer
      cert-manager.io/private-key-algorithm: ECDSA
      cert-manager.io/private-key-rotation-policy: Always
      traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
      helm.sh/resource-policy: keep
