postgresql:
  primary:
    service:
      type: LoadBalancer
      annotations:
        metallb.io/loadBalancerIPs: 192.168.1.26
    persistence:
      existingClaim: "postgresql"
    metrics:
      enabled: true
