apiVersion: v2
name: prometheus
type: application
version: 1.0.166
# renovate: image=quay.io/prometheus/prometheus
appVersion: "v3.9.0"
dependencies: 
  - name: prometheus
    version: "28.2.0"
    repository: https://prometheus-community.github.io/helm-charts
