apiVersion: v2
name: prometheus
type: application
version: 1.0.172
# renovate: image=quay.io/prometheus/prometheus
appVersion: "v3.9.1"
dependencies: 
  - name: prometheus
    version: "28.5.2"
    repository: https://prometheus-community.github.io/helm-charts
