apiVersion: v2
name: prometheus
type: application
version: 1.0.94
# renovate: image=quay.io/prometheus/prometheus
appVersion: "v3.1.0"
dependencies: 
  - name: prometheus
    version: "26.0.1"
    repository: https://prometheus-community.github.io/helm-charts
