apiVersion: v2
name: prometheus
type: application
version: 1.0.156
# renovate: image=quay.io/prometheus/prometheus
appVersion: "v3.7.3"
dependencies: 
  - name: prometheus
    version: "27.46.0"
    repository: https://prometheus-community.github.io/helm-charts
