apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
dependencies: 
  - name: grafana
    version: "6.50.0"
    repository: https://grafana.github.io/helm-charts

