apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.192
# renovate: image=grafana/grafana
appVersion: "12.2.2"
dependencies: 
  - name: grafana
    version: "10.1.4"
    repository: https://grafana.github.io/helm-charts

