apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.212
# renovate: image=grafana/grafana
appVersion: "12.3.1"
dependencies: 
  - name: grafana
    version: "10.5.10"
    repository: https://grafana.github.io/helm-charts

