apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.136
# renovate: image=grafana/grafana
appVersion: "11.4.0"
dependencies: 
  - name: grafana
    version: "8.8.1"
    repository: https://grafana.github.io/helm-charts

