apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.193
# renovate: image=grafana/grafana
appVersion: "12.3.0"
dependencies: 
  - name: grafana
    version: "10.1.5"
    repository: https://grafana.github.io/helm-charts

