apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.50
# renovate: image=grafana/grafana
appVersion: "10.1.4"
dependencies: 
  - name: grafana
    version: "6.60.1"
    repository: https://grafana.github.io/helm-charts

