apiVersion: v2
name: grafana
description: A Helm chart for Kubernetes
type: application
version: 1.0.215
# renovate: image=grafana/grafana
appVersion: "12.3.2"
dependencies: 
  - name: grafana
    version: "10.5.15"
    repository: https://grafana.github.io/helm-charts

