image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.12.4@sha256:75ef6851d2e48d366764cdb6b569b7ad8be77dcc8e0d1b9aa508ac90e42d4c58
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
