image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.11.2@sha256:02f582ea7d25f41761282ac0965baf89f0009efed3ad92f8d7eaba5eb6ffd9a8
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
