image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.11.3@sha256:f971850a6ec1fb5c5fd4e1748058e9e1f589aaf0da933b8d88bb5dee03f5b5e8
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
