image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.12.3@sha256:c9da2a0a5738ceb26e1b4f672825c09371e51ae5e285beffa3072757b7817f3e
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
