image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.12.2@sha256:60dd3a329324b92017b7c8665648d65a9568a5a4205e93cad67ab9dec432f2d1
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
