image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.12.5@sha256:9a5a3eb4a213dfb25932dee9dc6815c9305f78cecb5afa716fa2483163d8fb5b
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
