image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2026.2.3@sha256:96fa92d83fa8dae987fbbbcf58b1fea1140985ff6a8517b37f7b65c76ef20133
nfs:
  server: 192.168.1.5
  path: /nfs/home-assistant
