image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.12.0@sha256:8951fcbb794da8f261e1639c668639bc90f9520b48099b5715f6d5fbfef08a0e
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
