image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2026.1.0@sha256:97d63b3d0028b6b52ad8e5ac7b014c3404e69bf1656b5489eec48b59184e0bc7
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
