image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2025.12.1@sha256:4e5e81917192e3fa730948964b19d6e03ff3b9c2694894bc6d6b76769e642055
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
