image:
  repository: ghcr.io/home-assistant/home-assistant
  tag: 2026.1.1@sha256:bf1602fc889bc4e6e4c1ccf9e6657f0be968bda13e1a4d1299e3dbe0ccf9a23b
nfs:
  server: 192.168.1.4
  path: /nfs/home-assistant
