image:
  repository: "ghcr.io/deconz-community/deconz-docker"
  tag: "stable@sha256:c6128b0dbbb2beed59d7113825cbab4490a8447e90ff6a9dd834d27f6ce4cb8c"
vnc:
  mode: "1"
  password: AgAIAK53Epsj/hO3+ghNZpK6+NZAvbG/1QLXqlEiy86LtQo16lAZCkIZpiVVbqwpYF6Ca+JrT1ZiHZci5hCHNQ3CjgNznVxc5+pQoc0YRyzqSYINvSN7d4DAS2FSWxqqXOx/XynSu0mIez4z2QdogZGx+mKzWBuYdJtqkYC7B9EtKn19OpAvgsf6x0sd6a2u3HcpDpbQB2IKWrbues4Y54ZTU+5XEE5VVzKC6t5LyKmfhAJJjO6UkQOiZ1INWKoQS1g+1oJAeYBVE7iIz32IROhyUw3XLj5aSHZNgFL7bm2BkzTG0SQ8Nc4EORISFf7phVXJ8vyEis2GQME42uwbhfr2RxmFRoTffCzO2Fpo4A/5K+fgVSjBFwlyv3xouTH9t0/2GsVXIO8GAeP5Z22bOREwqlJdBeeFOKJETpV1W+FBqef1OF0uFTCxKsgdaKrI91OZv5TST2Sm00xSLEfWiXzjC+FGuuwfHODBYq2B6hJ5Did520t0Ioa3l0GKNzCVBRzeKjAPR3EPmBjCQi2im0S0BxiM+jMsxxlzAeEPjyYL9IY8MO4BcqeOBZVNQM738Vd4stYjdg61f3ZYc5hpy6oknIjA58r3XvywAmtTsLdCEawfKs0mXDigbi3VkmyWqW0tZU099BA9uUr+OfZwJBNzmvmoWBz0QyW32f02kxOQxpnarlr2XFBJW+SvwULzy7ZVSZtPrtwr2ovC1X0=
nfs:
  server: 192.168.1.4
  path: "/nfs/deconz"
