csi-driver-nfs:
  externalSnapshotter:
    enabled: true
  controller:
    runOnControlPlane: true
    replicas: 2
  storageClass:
    create: true
    name: nfs
    annotations:
      storageclass.kubernetes.io/is-default-class: "true"
    parameters:
      server: 192.168.1.5
      share: /nfs
      subDir: ${pvc.metadata.namespace}-${pvc.metadata.name}
      mountPermissions: "0755"
    reclaimPolicy: Retain
    volumeBindingMode: Immediate
    mountOptions:
      - nfsvers=4.1
      - rsize=1048576
      - wsize=1048576
      - hard
      - timeo=600
      - retrans=2
      - noatime
  volumeSnapshotClass:
    create: true
    name: volume-snapshot-class
    deletionPolicy: Delete
