image:
  repository: adguard/adguardhome
  tag: v0.107.71@sha256:92929135ced2554aaf94706f766a98ad348f211df61b0704e2db7e8498cc00b7
nfs:
  server: 192.168.1.4
  path: /nfs/adguard
service:
  loadBalancerIPs: 192.168.1.20, fd::20
