image:
  repository: adguard/adguardhome
  tag: v0.107.72@sha256:4956b35b590286e5872fb4336d84a7862a2030c6efb4ca16442580c37d7ba32d
service:
  loadBalancerIPs: 192.168.1.20, fd7c:3b4a:5f1d::20
nfs:
  server: 192.168.1.5
  path: /nfs/adguard
