image:
  repository: adguard/adguardhome
  tag: v0.107.71@sha256:92929135ced2554aaf94706f766a98ad348f211df61b0704e2db7e8498cc00b7
service:
  loadBalancerIPs: 192.168.1.20, fd7c:3b4a:5f1d::20
nfs:
  server: 192.168.1.5
  path: /nfs/adguard
