nfs:
  server: 192.168.1.5
  path: /nfs/victoria-metrics

victoria-metrics:
  server:
    persistentVolume:
      existingClaim: victoria-metrics
    ingress:
      enabled: true
      annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-https-redirect@kubernetescrd
      ingressClassName: "traefik"
      hosts:
        - name: victoria-metrics.burau.dev
          path:
            - /
          port: http
        - name: vm.burau.dev
          path:
            - /
          port: http       
      tls:
        - secretName: ingress-tls
          hosts:
            - victoria-metrics.burau.dev
            - vm.burau.dev
    service:
      clusterIP: ""

