image:
  repository: "nodered/node-red"
  tag: "4.1.2-20@sha256:216e7403aab9888f7e68de9e468fed31bb9d7b2d38117c08e645095a63658a2f"
nfs:
  server: 192.168.1.4
  path: "/nfs/node-red"
env:
  - name: NRCHKB_EXPERIMENTAL
    value: "true"
