image:
  repository: ghcr.io/koenkk/zigbee2mqtt
  tag: 2.7.2@sha256:60a295b40f4e7fb7ab4d995932369e50f2529837272fa4979e986ec1ffdb7fce
port: 8080
timezone: Europe/Berlin
nfs:
  server: 192.168.1.4
  path: "/nfs/zigbee2mqtt"
