image:
  repository: ghcr.io/koenkk/zigbee2mqtt
  tag: 2.7.1@sha256:163e7351430a95d550d5b1bb958527edc1eff115eb013ca627f3545a192e853f
port: 8080
timezone: Europe/Berlin
nfs:
  server: 192.168.1.4
  path: "/nfs/zigbee2mqtt"
