image:
  repository: ghcr.io/koenkk/zigbee2mqtt
  tag: 2.7.0@sha256:7da30df2c3e53ea02e0bbce0241306358e946b2b5ce6ec02ecdf90be0a96c694
port: 8080
timezone: Europe/Berlin
nfs:
  server: 192.168.1.4
  path: "/nfs/zigbee2mqtt"
