service:
  loadBalancerIPs: 192.168.1.33,fd7c:3b4a:5f1d::33

cloudflare-api-token: AgBZJSJO5KZK187j3aRWiHC/rRCHRuBk46RUGtFu0hPI4YP1AiIsqmytP2O1AUds9jtQHGB7hbxUj8myZdkvx/t+SJJQtrrAmibDGd3fV8quQRWh5yPBb1024+hiGcV7iYh4qL5Lr8Clw4ixGfOfByknqvuSn7KXrh6lHqtAcbx1leHuozAPhZnRixbz3yO9F+1Bq+c6BewacFotbuWfCsG189hSZdk5fhZQv9n5R49J6Aed+UCTJD+M16LctEGAYssn/DcMHhfCDJxEGSGk2rKVCr85tHGIXN9P4Ubm9U3WF/kYIKcVPPWh4Mw1VcDwlu6UsM3vNHBDw8bsvv+yjnrxglq+BCQvjKRSfSbeUuLrbOVfbBiS1Fp6Kte3J4Q4iOrNglyFeU/8RG/c3iWQ/pCYOF+h8QZLok29icdRd2D+FNEClHf9psDG7F04GNRDq1Zt14jDAzk0fJAx7AOUFLzmVu1YUKkx3dVJ0pK5/T9xOzdcwWmPWqwflXFQIdrqJSrs9iCnOKwJQTctZSVS6bD6AVv3Dq1a0jyOJiKqhxk1AZkOpdvgBheMtRL1GRcqnWKwqcWvSkCTpK789T9SsDdN8idxGP488nPKeBKn55QrVSUZweOll2DgdUQHmo3qj6cyMI7YMTnJ0gCq96b+B1kKQkEP8vjjZt3SA8VAziAHQNAat6bMaaLc+cG9pcot6IzASIONGsl/fghp+CrJYzw6xhHnuYiPFWTMQNZAjPnl1WCSIN5PbbVj

cert-manager:
  installCRDs: true
  enableCertificateOwnerRef: true
