service:
  loadBalancerIPs: 192.168.1.33,fd7c:3b4a:5f1d::33

cloudflare-api-token: AgCLM4CvDHzf+v9PDSjlyJIQy82Dk3DJMR4Er2QrMbtIZcK+8siuFAigFadCn/4wsEbc4glH874IuAIjVVvnrq+jJph23lCNwND7yxkWGBvZnVK5RTo/pvN9ZsHnwiybU/eAJxMWN1/WEJp/Rtg272kal+esJ3dwu7m9DlUizTqEHmfxImnWbLPMOO3sHLCY1qlkErQvZQwv7RnAL7fOKX5464UuB/kyq7r21iqsSIQD+Ki2ek4jsuNX3an2vzA5+dtFFXp/fyIxHj+ROR8R0pHIAxdVjIktvPGAeQ1DZuzH4r25p0OLdjWlz7NEv5Vz5nMw550gUqYUDOo/lhg+4wvRnox+Gd+HLkC0t5rqIgXuCUIqjWLuF/bS3y47kf7LqREK097fYGb3A4JAn3VvJdsIbPvGXJ1g9Jh8s+O0ndXYOX2IsVHhrhVwxlwQojzoL8VDcvj+cugvQRPHuQdeBiMidKs9BPLGWNl32WUElv7xN+oU/v16X+USp+v6Mt0GFxB+dHuMpaWne8efK37a/K7dpRNNU4O4Tqwrea3pRNdDg0JC8CvSCWqXJ4zN+JKm9+BjTBevM09Yef/KGF7mNs6l24J3jnTLVcgBMTXYYEw9cp+tKwcBG6ZNNk7LiEKlBdG9rrRMLaf2QF1Zvur0ofVrvoMGuy4ZChqtj4W56lBQyyx+rpBEJdXEftiYMghc997yWJozp4pI6q769gW3B/I/uSYHtcgezThzqXt2fKfLbQ4BW/S/BZXg

cert-manager:
  installCRDs: true
  enableCertificateOwnerRef: true
