service:
  loadBalancerIPs: 192.168.1.33,fd7c:3b4a:5f1d::33

cloudflare-api-token: AgCj/1CKAoQYsr37Yjd/omyHz0i/EELVDYjkA8L47qyyVjfqu6Bz/luc8BnsCvmuTgqnU0404KyRZADRfU90FuJzwLqduYh5swKCoM6/oI5E9YRjJRoa+3l38OTSHAO3w3E62MdbKVn6hUcnN9+9dcbpT8ALpa1iG9mVz+nE2Y5X/FbxKWn/T770ehynnatE7MUrqx3Ft19w/C+4WcgclbiI9rwDZ5y+6C0tSIhFrcgMXMvRL+z2SA891TYyl+Y0CsHTfEFwLsnheCgwNXRREOUxb/SHKwXyDFqjbjNoIhMeXDbsG6UVz/6qz5vfyXzGLVTk4R/YZD0xcv8EnzvyRR3iiN6UDz3xu+t+0CsWDt2gius+4m9JqBwwklOvB8BkdJWeVewdbTtzhZMfCaXABTAoY4sETfZwZa0jUvEEpSsJzQbnMDCuN3ouUhxrYieiQpmQtej3ezLU+jIZnHz15UxNsl8ZvShz5QLPHrYtcgY6L+Cur9j0rTfHqtuG31SL8d0tnF4oxuDDdTdgy4Nd7QP3SbyG3obEX/ll/TcOi1IlBorVJFowsTi7ioQ+6kxI/7tOUh9VxjM2J/9J7lOZ0YMmlxpZNN8wWAbea9g6iaGM7A/BV7gxNGodV+g7yqUYEkZsk8ZhRZ8I+951G1CvPK4Q//5IUWfBmxd4W7DKRiYVx30XuF+wfxyJP4vUyJ1hWWYCXmgzOowDXZgFNnukpGG1jbIgdGQNRzhoeRDtWNCvZAQctv1Snv9S

cert-manager:
  installCRDs: true
  enableCertificateOwnerRef: true
